imageboard/urls.py
from django.urls import path

from . import views, api


app_name = 'imageboard'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('signup/', views.registration, name='signup'),
    path('upload/', views.post_image, name='upload'),
    path('search/', views.SearchResultsView.as_view(), name='results'),
    path('<int:post_id>/', views.get_detail, name='view'),
    path('comment/<int:post_id>/',views.post_comment, name='comment'),
    path('tag/<int:post_id>/', views.add_tag, name='tag'),
    path('logout/', views.logout_view, name='logout'),
    path('api/tags', api.get_all_tagnames_sqlite3, name='apitags')
]

randosite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('imageboard/', include('imageboard.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/profile/', profile_view, name='profile'),
    path('', redir)
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

imageboard/models.py
from django.db import models
from django.contrib.auth.models import User


class Posting(models.Model):
    title = models.CharField(max_length=50)
    upload_date = models.DateTimeField(auto_now=True)
    file = models.ImageField(upload_to='imageboard')
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=0)


class Comment(models.Model):
    posted_at = models.DateTimeField(auto_now=True)
    content = models.CharField(max_length=200)
    post = models.ForeignKey(Posting, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)


class Tag(models.Model):
    name = models.CharField(max_length=40)
    post = models.ForeignKey(Posting, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('post', 'name')

imageboard/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class PostForm(forms.ModelForm):
    """imageboard posts"""
    class Meta:
        model = Posting
        fields = ('title', 'file')


class SignUpForm(forms.ModelForm):
    """user signup"""
    class Meta:
        model = User
        fields = ('username', 'password')


class CommentForm(forms.ModelForm):
    """user comments"""
    class Meta:
        model = Comment
        fields = ('content',)

class TagForm(forms.ModelForm):
    """adding tags"""
    class Meta:
        model = Tag
        fields = ('name',)

    def clean_name(self):
        data = self.cleaned_data['name']
        if ' ' in data:
            raise ValidationError("Tag cannot contain whitespace")

        return data

imageboard/views.py
from django.shortcuts import get_list_or_404, redirect, render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.http import Http404, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

from .models import *
from .forms import *
from .tags import process_query, OPERATORS
from .esets import EmptySet

BOARDNAME = "727Chan"

class IndexView(generic.ListView):
    template_name = 'imageboard/index.html'
    context_object_name = 'postlist'

    def get_queryset(self):
        """returns all posts sorted by published date"""

        return Posting.objects.order_by('-upload_date')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['boardname'] = BOARDNAME
        ctx['digits'] = str(Posting.objects.count())
        return ctx



class SearchResultsView(generic.ListView):
    template_name = 'imageboard/results.html'
    context_object_name = 'results'

    def get_queryset(self):
        expression = self.request.GET.get('q')
        or_tags, and_tags, exclude_tags = process_query(expression)

        or_results = None
        and_results = None
        exclude_results = None

        # process or's:
        for tags1,tags2 in or_tags:
            pairing = Posting.objects.none()
            for tp_pairing in tags1:
                pairing |= Posting.objects.filter(pk=tp_pairing.post_id)

            for tp_pairing in tags2:
                pairing |= Posting.objects.filter(pk=tp_pairing.post_id)

            if or_results is None:
                or_results = pairing
            else:
                or_results &= pairing

                

        # process and's:
        iresult = Posting.objects.none()
        try:
            currname = and_tags.first().name
        except:
            currname = ""
        for tp_pair in and_tags:

            if tp_pair.name != currname:
                if and_results is None:
                    and_results = iresult
                else:
                    and_results &= iresult
                iresult = Posting.objects.filter(pk=tp_pair.post_id)
                currname = tp_pair.name
                continue

            iresult |= Posting.objects.filter(pk=tp_pair.post_id)

        if iresult.exists():
            if and_results is None:
                and_results = iresult
            else:
                and_results &= iresult

            

        # process excludes
        for tag in exclude_tags:
            iresult = Posting.objects.filter(pk=tag.post_id)

            if exclude_results is None:
                exclude_results = iresult
            else:
                exclude_results |= iresult


        if exclude_results is None:
            exclude_results = self.qs_return_empty()
        if and_results is None:
            and_results = EmptySet(model=Posting).none()
        if or_results is None:
            or_results = EmptySet(model=Posting).none()
        


        if isinstance(and_results, EmptySet) and isinstance(or_results, EmptySet):
            return Posting.objects.all().difference(exclude_results)
        
        if isinstance(and_results, EmptySet):
            return (and_results & or_results).difference(exclude_results)
        
        return (or_results & and_results).difference(exclude_results).order_by('-upload_date')
        


    def qs_return_empty(self):
        return Posting.objects.none()

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['expression'] = self.request.GET.get('q').split(' ')
        ctx['boardname'] = BOARDNAME
        ctx['keywords'] = OPERATORS
        ctx['digits'] = str(Posting.objects.count())
        return ctx


def trace_postset(qs, name=None):
    if qs is None:
        if name:
            print("{} is None".format(name))
        else:
            print("None")
        return
    if name:
        print('\n{0} {1}:'.format(qs, name))
    else:
        print('\n{}:'.format(qs))
    for item in qs:
        print(' {0}: {1}'.format(item, item.title))
    print('end of QuerySet\n')

def trace_tp(tp, name=None):
    if tp is None:
        if name:
            print("{} is None".format(name))
        else:
            print("None")
        return
    if name:
        print('\n{0} {1}:'.format(tp, name))
    else:
        print('\n{}:'.format(tp))

    print('  tag {0} paired with post {1}'.format(tp.name, tp.post.title))

def get_detail(request, post_id):
    try:
        post = get_object_or_404(Posting, pk=post_id)
    except Http404:
        return render(request, 'imageboard/error.html', {
            'message': 'Post not found (404)',
            'boardname': BOARDNAME
        })

    comments = Comment.objects.filter(post_id=post_id)
    tags = Tag.objects.filter(post_id=post_id)

    return render(request, 'imageboard/viewpost.html', {
        'post': post,
        'tags': tags,
        'comments': comments,
        'boardname': BOARDNAME
    })


def registration(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.instance.set_password(request.POST['password'])
            form.save()
            return HttpResponseRedirect(reverse('imageboard:index'))
    
    else:
        form = SignUpForm()

    return render(request, 'registration/register.html', {
        'form': form,
        'boardname': BOARDNAME
    })


@login_required
def post_image(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.author = request.user
            form.save()
            return HttpResponseRedirect(reverse('imageboard:index'))
    else:
        form = PostForm()
    
    return render(request, 'imageboard/upload.html', {
        'form': form,
        'boardname': BOARDNAME
    })


@login_required
def post_comment(request, post_id):

    try:
        parent_post = get_object_or_404(Posting, pk=post_id)
    except Http404:
        return render(request, 'imageboard/error.html', {
            'message': 'Parent post not found (404)',
            'boardname': BOARDNAME
        })

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():

            form.instance.author = request.user
            form.instance.post = parent_post
            form.save()

            return HttpResponseRedirect(reverse('imageboard:view', kwargs={'post_id': post_id}))
    else:
        form = CommentForm()

    return render(request, 'imageboard/comment.html', {
        'post': parent_post,
        'form': form,
        'boardname': BOARDNAME
    })
            

@login_required
def add_tag(request, post_id):
    try:
        parent_post = get_object_or_404(Posting, pk=post_id)
    except Http404:
        return render(request, 'imageboard/error.html', {
            'message': 'Parent post not found (404)',
            'boardname': BOARDNAME
        })

    if request.method == 'POST':
        form = TagForm(request.POST)

        if form.is_valid():

            form.instance.post = parent_post
            try:
                form.save()
            except Exception as e:
                return render(request, 'imageboard/tag.html', {
                    'post': parent_post,
                    'form': form,
                    'boardname': BOARDNAME,
                    'error': e
                })

            return HttpResponseRedirect(reverse('imageboard:view', kwargs={'post_id': post_id}))
    else:
        form = TagForm()

    return render(request, 'imageboard/tag.html', {
        'post': parent_post,
        'form': form,
        'boardname': BOARDNAME
    })


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('imageboard:index'))

imageboard/templates/imageboard/comment.html
{% extends 'base.html' %}

{% block title %}comment{% endblock %}
{% load static %}
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'imageboard/comment.css' %}" />
{% endblock %}
{% block content %}


{% if form.errors %}
<div class="alert alert-danger">
    <strong>Something is wrong with your comment. Please try again.</strong>
    {% for field in form %}
        {% for error in field.errors %}
        <p>{{ error|escape }}</p>
        {% endfor %}
    {% endfor %}
</div>
{% endif %}
<h1 class="text-center" id="comment-title">Post a comment</h1>
<form class="border rounded" id="comment-form" method="post" action="{% url 'imageboard:comment' post.id %}">
    {% csrf_token %}
    <div class="row mb-3">
        <label id="comment-text-label" for="comment-field" class="col-sm-1 col-form-label">Comment</label>
        <div class="col-sm-10">
            <input class="form-control" type="text" name="content" maxlength="250" required id="comment-field">
        </div>
    </div>
    <input class="btn btn-outline-light" type="submit" value="Comment!">
</form>
{% endblock  %}

imageboard/templates/imageboard/error.html
{% extends 'base.html' %}
{% block title %}Error{% endblock %}
{% block content %}
<h1>Oh no! Something went wrong!</h1>
<p>{{ message }}</p>
{% endblock  %}

imageboard/templates/imageboard/index.html
{% extends 'base.html' %}
{% block title %}Listing{% endblock %}

{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'imageboard/index.css' %}">
{% endblock %}

{% block content %}
<div id="moe-counter">
    {% for digit in digits %}
    <img class="count-digit" src="{% static 'imageboard/' %}{{ digit }}.gif" alt="{{ digit }}.gif">
    {% endfor %}
</div>
<div class="search">
    <p>Perform a search! (Note: nonexistent tags in the search query will be ignored)</p>
    <form action="{% url 'imageboard:results' %}" method="get">
        <div class="border rounded" id="search-form">
            <input class="search-form-item" id="autocomplete" name="q" placeholder="Search">
            <input class="search-form-item btn btn-outline-light" type="submit" value="search">
        </div>
    </form>
</div>
<h2 class="text-center">Posts</h2>
<div id="posts-container" class="border rounded">
    {% for post in postlist %}
    <div class="post-preview">
        <a href="{% url 'imageboard:view' post.id %}">
            <img class="border border-success border-3" src="{{ post.file.url }}" alt="{{ post.file.url }}" style="max-width: 100px;">
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}

{% block scripts %}
<script>
    const headers = {
        Accept: "application/json",
    };
    var searchStringSoFar = "";
    var completion = "";
    fetch("{% url 'imageboard:apitags' %}", {
        headers: headers,
    })
        .then((response) => response.json())
        .then((data) => {
            $("#autocomplete").autocomplete({
                source: data.tags,
                search: function(event, ui) {
                    var s = event.target.value;
                    if (s == "") {
                        searchStringSoFar = s;
                    } else {
                        let tokens = s.split(" ");
                        tokens.pop();
                        searchStringSoFar = tokens.join(" ");
                    }
                },
                select: function (event, ui) {
                    completion = searchStringSoFar + " " + ui.item.value;
                },
                close: function (event, ui) {
                    if (completion != "") {
                        event.target.value = completion;
                    }
                    completion = "";
                }
            });
        });
</script>
{% endblock %}

imageboard/templates/imageboard/results.html
{% extends 'base.html' %}

{% block title %}Search Results{% endblock %}

{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'imageboard/index.css' %}">
{% endblock %}

{% block content %}
<div id="moe-counter">
    {% for digit in digits %}
    <img class="count-digit" src="{% static 'imageboard/' %}{{ digit }}.gif" alt="{{ digit }}.gif">
    {% endfor %}
</div>
<div class="search">
    <p>Perform a search! (Note: nonexistent tags in the search query will be ignored)</p>
    <form action="{% url 'imageboard:results' %}" method="get">
        <div class="border rounded" id="search-form">
            <input class="search-form-item" id="autocomplete" name="q" placeholder="Search">
            <input class="search-form-item btn btn-outline-light" type="submit" value="search">
        </div>
    </form>
</div>
<h2 class="text-center">Search results for "
    {% for token in expression %}
        {% if token in keywords %}
        <span class="syntax-kw">{{ token }}</span>
        {% else %}
        <span class="syntax-regular">{{ token }}</span>
        {% endif %}
    {% endfor %}":</h2>
<div id="posts-container" class="border rounded">
    {% for post in results %}
    <div class="post-preview">
        <a href="{% url 'imageboard:view' post.id %}">
            <img class="border border-success border-3" src="{{ post.file.url }}" alt="{{ post.file.url }}" style="max-width: 100px;">
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}

{% block scripts %}
<script>
    const headers = {
        Accept: "application/json",
    };
    var searchStringSoFar = "";
    var completion = "";
    fetch("{% url 'imageboard:apitags' %}", {
        headers: headers,
    })
        .then((response) => response.json())
        .then((data) => {
            $("#autocomplete").autocomplete({
                source: data.tags,
                search: function(event, ui) {
                    var s = event.target.value;
                    if (s == "") {
                        searchStringSoFar = s;
                    } else {
                        let tokens = s.split(" ");
                        tokens.pop();
                        searchStringSoFar = tokens.join(" ");
                    }
                },
                select: function (event, ui) {
                    completion = searchStringSoFar + " " + ui.item.value;
                },
                close: function (event, ui) {
                    if (completion != "") {
                        event.target.value = completion;
                    }
                    completion = "";
                }
            });
        });
</script>
{% endblock %}

imageboard/templates/imageboard/tag.html
{% extends 'base.html' %}
{% block title %}Add Tag{% endblock %}
{% load static %}
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'imageboard/tag.css' %}" />
{% endblock %}
{% block content %}
{% if error %}
<div class="alert alert-danger text-center">
    <strong>ERROR: {{ error|escape }}</strong>
</div>
{% endif %}
{% if form.errors %}
<p>Something is wrong with your tag. Please try again.</p>
<p>Errors found:</p>
{% for field in form %}
    {% for error in field.errors %}
    <div class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
    </div>
    {% endfor %}
{% endfor %}
{% endif %}
<h1 class="text-center" id="tag-title">Add a tag to this post</h1>
<form class="border rounded" id="tag-form" method="post" action="{% url 'imageboard:tag' post.id %}">
    {% csrf_token %}
    <div class="row mb-3">
        <label id="tagname-label" for="tagname-field" class="col-sm-1 col-form-label">Tag</label>
        <div class="col-sm-10">
            <input class="form-control" type="text" name="name" maxlength="100" required id="tagname-field">
        </div>
    </div>
    <input class="btn btn-outline-light" type="submit" value="Add tag">
</form>
{% endblock %}

imageboard/templates/imageboard/upload.html
{% extends 'base.html' %}
{% block title %}Upload{% endblock %}
{% load static %}
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'imageboard/upload.css' %}" />
{% endblock %}
{% block content %}

{% if form.errors %}
<div class="error-indication alert alert-danger text-center">
    <strong>
        There is something wrong with your post. Please try again.
    </strong>
</div>
{% endif %}
<h1 class="text-center" id="upload-title">Upload an image!</h1>
<form class="border rounded" id="upload-form" enctype="multipart/form-data" method="post" action="{% url 'imageboard:upload' %}">
    {% csrf_token %}
    <div class="row mb-3">
        <label for="title-field" class="upload-form-label col-sm-1 col-form-label">Title</label>
        <div class="col-sm-10">
            <input class="form-control" type="text" name="title" id="title-field" maxlength="100" required>
        </div>
    </div>
    <div class="row mb-3">
        <label for="file-field" class="upload-form-label col-sm-1 col-form-label">File</label>
        <div class="col-sm-10">
            <input class="form-control" type="file" name="file" accept="image/*" required id="file-field">
        </div>
    </div>
    <input class="btn btn-outline-light" type="submit" value="Post!">
</form>
{% endblock  %}

imageboard/templates/imageboard/viewpost.html
{% extends 'base.html' %} {% block title %}View{% endblock %} {% load static %}
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'imageboard/view.css' %}" />
{% endblock %} {% block content %}
<div class="search">
  <p>
    Perform a search! (Note: nonexistent tags in the search query will be
    ignored)
  </p>
  <form action="{% url 'imageboard:results' %}" method="get">
    <div class="border rounded" id="search-form">
      <input
        class="search-form-item"
        id="autocomplete"
        name="q"
        placeholder="Search"
      />
      <input
        class="search-form-item btn btn-outline-light"
        type="submit"
        value="search"
      />
    </div>
  </form>
</div>
<div class="post-info text-center">
  <h2>{{ post.title }}</h2>
  <p>posted by {{ post.author.username }} on {{ post.upload_date }} UTC</p>
</div>
<div id="post-container">
  <div id="tags-container" class="post-container-item border rounded">
    <p>Tags</p>
    {% for tag in tags %}
    <div class="tag">
      <a href="{% url 'imageboard:results' %}?q={{ tag.name }}"
        >{{ tag.name }}</a
      >
    </div>
    {% endfor %}
    <div id="tag-button-buffer"></div>
    <a class="btn btn-outline-light" href="{% url 'imageboard:tag' post.id %}">Add a tag</a>
  </div>
  <img
    id="post-image"
    class="post-container-item"
    src="{{ post.file.url }}"
    alt="{{ post.file.url }}"
    style="max-width: 85%"
  />
</div>
<div id="comments-container">
  <div class="comments-header text-center">
    <p class="display-3">Comments</p>
    <a class="btn btn-outline-light" href="{% url 'imageboard:comment' post.id %}">Post a comment!</a>
  </div>
  {% for comment in comments %}
  <div class="comment border rounded">
    <p class="comment-author">{{ comment.author.username }}:</p>
    <p class="comment-content">{{ comment.content }}</p>
  </div>
  {% endfor %}
</div>
{% endblock %} {% block scripts %}
<script>
  const headers = {
    Accept: "application/json",
  };
  var searchStringSoFar = "";
  var completion = "";
  fetch("{% url 'imageboard:apitags' %}", {
    headers: headers,
  })
    .then((response) => response.json())
    .then((data) => {
      $("#autocomplete").autocomplete({
        source: data.tags,
        search: function (event, ui) {
          var s = event.target.value;
          if (s == "") {
            searchStringSoFar = s;
          } else {
            let tokens = s.split(" ");
            tokens.pop();
            searchStringSoFar = tokens.join(" ");
          }
        },
        select: function (event, ui) {
          completion = searchStringSoFar + " " + ui.item.value;
        },
        close: function (event, ui) {
          if (completion != "") {
            event.target.value = completion;
          }
          completion = "";
        },
      });
    });
</script>
{% endblock %}